### ISSUE TITLE
Wifi manager not initialized error

### ISSUE THREAD

**Issue by xunreal75** [ksenia312/nearby_service#8]
Exception will be thrown on
Android devices

62% Android 14
12% Android 13
7% Android 10
6% Android 15
13% other (5)

Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {de.bladenight.bladenight_app_flutter/de.bladenight.bladenight_app_flutter.MainActivity}: wj.s: lateinit property wifiManager has not been initialized
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5901)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5933)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:282)
       at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:150)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loopOnce(Looper.java:232)
       at android.os.Looper.loop(Looper.java:317)
       at android.app.ActivityThread.main(ActivityThread.java:8592)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
        

Caused by wj.s

          Caused by wj.s: lateinit property wifiManager has not been initialized
       at com.xenikii.nearby_service.NearbyServiceManager.disconnect(NearbyServiceManager.java:15)
       at com.xenikii.nearby_service.NearbyServiceManager.disconnect$default(NearbyServiceManager.java:5)
       at com.xenikii.nearby_service.NearbyServicePlugin.onDetachedFromEngine(NearbyServicePlugin.java:56)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:122)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:16)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll(FlutterEngineConnectionRegistry.java:11)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(FlutterEngineConnectionRegistry.java:10)
       at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:31)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:105)
       at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:18)
       at android.app.Activity.performDestroy(Activity.java:9251)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1561)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5888)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5933)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:282)
       at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:150)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loopOnce(Looper.java:232)
       at android.os.Looper.loop(Looper.java:317)
       at android.app.ActivityThread.main(ActivityThread.java:8592)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

Issue is monitored by Chrashlytics

**Comment by ksenia312** [comment]
Hello! @xunreal75 
I've never seen that error, but I'll try to check it out soon!

**Comment by ksenia312** [comment]
@xunreal75 I checked everything, found the problem by your comment, thanks!

The bug is fixed, I will test it and publish a new version soon!
